### ISSUE TITLE
Login page logo issue

### ISSUE THREAD

**Issue by Eli-Par** [zayatMark/3220-group-project#8]
On the login page (/login), the logos of the different sites display but also have a file not found icon overlayed on them. There is also some spacing issues with the logos bring directly next to each other.

![Data-Portal-Login-Image-Issue](https://github.com/zayatMark/3220-group-project/assets/59713280/878a3a6a-e0b6-4b7c-a6a6-340babbf997a)

**Comment by Eli-Par** [comment]
This issue does not occur on Firefox and likely only occurs on chromium based browsers.

**Comment by keerat03** [comment]
chromium based browser issue was resolved, with changes to attributes.
